Vagrant.configure("2") do |config|

    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :private_network, ip: "192.168.33.101"

    config.vm.provision "chef_solo" do |chef|
        chef.add_recipe "main"
    end

    config.vm.synced_folder "../testapp", "/vagrant", :nfs => true

end