#Vagrantfile - Puppet
Vagrant.configure("2") do |config|

    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :private_network, ip: "192.168.33.103"
    config.ssh.forward_agent = true

    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 1024]
    end

    config.vm.synced_folder "../../application/", "/vagrant", id: "vagrant-root", :nfs => true

    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "main.pp"
        puppet.module_path = "modules"
        puppet.options = ['--verbose']
    end

end