Vagrant.configure("2") do |config|

    config.vm.box = "digital_ocean"
    config.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    config.ssh.private_key_path = "~/.ssh/id_rsa"

    config.vm.provider :digital_ocean do |provider|
        provider.client_id = "YOUR_DIGITAL_OCEAN_CLIENT_ID"
        provider.api_key = "YOUR_DIGITAL_OCEAN_API_KEY"
        provider.image = "Ubuntu 12.04.3 x64"
        provider.region = "Amsterdam 2"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
    end

    config.vm.synced_folder "../testapp", "/vagrant"

end