Vagrant.configure("2") do |config|

    config.vm.box = "digital_ocean"
    config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    config.vm.provider :digital_ocean do |provider, override|
	override.ssh.private_key_path = '~/.ssh/vagrant_id_rsa'
        provider.token = 'YOUR_DIGITALOCEAN_API_TOKEN'
        provider.image = 'ubuntu-14-04-x64'
        provider.region = 'nyc2'
        provider.size = '512mb'
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
    end

    config.vm.synced_folder "../testapp", "/vagrant"

end
