Vagrant.configure("2") do |config|

    config.vm.box = "digital_ocean"
    config.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    config.ssh.private_key_path = "~/.ssh/id_rsa"

    config.vm.provider :digital_ocean do |provider|
        provider.token = 'YOUR TOKEN'
        provider.image = 'Ubuntu 14.04 x64'
        provider.region = 'nyc2'
        provider.size = '512mb'
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
    end

    config.vm.synced_folder "../testapp", "/vagrant"

end