Vagrant.configure("2") do |config|

    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :private_network, ip: "192.168.33.101"
    config.ssh.forward_agent = true

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.verbose = 'vv'
    end

    config.vm.synced_folder "../testapp", "/vagrant", id: "vagrant-root", :nfs => true
end